{
//=========Macro generated from canvas: c1/c1
//=========  (Mon Mar 22 21:17:47 2010) by ROOT version5.25/04
   TCanvas *c1 = new TCanvas("c1", "c1",299,94,700,544);
   c1->ToggleEventStatus();
   c1->Range(-0.8795332,-0.8506796,7.99228,4.579858);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetLogy();
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *deltaRLeptonPhotonStatus3NoFilter = new TH1F("deltaRLeptonPhotonStatus3NoFilter","W#gamma#rightarrowl#nu#gamma+nj, l=e,#mu, n=0,1",100,0,10);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(1,5803);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(2,1105);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(3,688);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(4,446);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(5,307);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(6,265);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(7,214);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(8,167);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(9,142);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(10,150);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(11,95);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(12,102);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(13,82);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(14,84);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(15,75);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(16,70);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(17,67);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(18,67);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(19,56);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(20,47);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(21,57);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(22,36);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(23,52);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(24,59);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(25,53);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(26,50);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(27,60);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(28,60);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(29,67);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(30,69);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(31,89);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(32,62);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(33,56);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(34,35);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(35,31);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(36,16);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(37,24);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(38,33);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(39,23);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(40,16);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(41,18);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(42,10);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(43,5);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(44,14);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(45,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(46,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(47,7);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(48,12);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(49,5);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(50,7);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(51,6);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(52,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(53,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(54,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(55,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(56,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(57,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(58,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(61,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(62,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(63,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(68,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(72,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(73,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(75,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(76,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(79,1);
   deltaRLeptonPhotonStatus3NoFilter->SetEntries(11100);
   
   TPaveStats *ptstats = new TPaveStats(0.6465517,0.6882591,0.8635057,0.8765182,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetLineColor(4);
   ptstats->SetTextAlign(12);
   ptstats->SetTextColor(4);
   TText *text = ptstats->AddText("deltaRLeptonPhotonStatus3NoFilter");
   text->SetTextSize(0.0432996);
   text = ptstats->AddText("Entries = 11100  ");
   text = ptstats->AddText("Mean  = 0.5345");
   text = ptstats->AddText("RMS   = 0.9382");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   deltaRLeptonPhotonStatus3NoFilter->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(deltaRLeptonPhotonStatus3NoFilter->GetListOfFunctions());
   deltaRLeptonPhotonStatus3NoFilter->SetLineColor(4);
   deltaRLeptonPhotonStatus3NoFilter->SetLineStyle(2);
   deltaRLeptonPhotonStatus3NoFilter->SetLineWidth(3);
   deltaRLeptonPhotonStatus3NoFilter->GetXaxis()->SetTitle("#DeltaR(l,#gamma) matrix element level");
   deltaRLeptonPhotonStatus3NoFilter->GetXaxis()->SetRange(1,71);
   deltaRLeptonPhotonStatus3NoFilter->GetYaxis()->SetTitle("Events");
   deltaRLeptonPhotonStatus3NoFilter->Draw("");
   
   TPaveText *pt = new TPaveText(0.01,0.9391296,0.3949425,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(1);
   text = pt->AddText("W#gamma#rightarrowl#nu#gamma+nj, l=e,#mu, n=0,1");
   pt->Draw();
   
   TH1F *deltaRLeptonPhotonStatus3 = new TH1F("deltaRLeptonPhotonStatus3","deltaR lepton photon status 3",100,0,10);
   deltaRLeptonPhotonStatus3->SetBinContent(4,446);
   deltaRLeptonPhotonStatus3->SetBinContent(5,307);
   deltaRLeptonPhotonStatus3->SetBinContent(6,265);
   deltaRLeptonPhotonStatus3->SetBinContent(7,214);
   deltaRLeptonPhotonStatus3->SetBinContent(8,167);
   deltaRLeptonPhotonStatus3->SetBinContent(9,142);
   deltaRLeptonPhotonStatus3->SetBinContent(10,150);
   deltaRLeptonPhotonStatus3->SetBinContent(11,95);
   deltaRLeptonPhotonStatus3->SetBinContent(12,102);
   deltaRLeptonPhotonStatus3->SetBinContent(13,82);
   deltaRLeptonPhotonStatus3->SetBinContent(14,84);
   deltaRLeptonPhotonStatus3->SetBinContent(15,75);
   deltaRLeptonPhotonStatus3->SetBinContent(16,70);
   deltaRLeptonPhotonStatus3->SetBinContent(17,67);
   deltaRLeptonPhotonStatus3->SetBinContent(18,67);
   deltaRLeptonPhotonStatus3->SetBinContent(19,56);
   deltaRLeptonPhotonStatus3->SetBinContent(20,47);
   deltaRLeptonPhotonStatus3->SetBinContent(21,57);
   deltaRLeptonPhotonStatus3->SetBinContent(22,36);
   deltaRLeptonPhotonStatus3->SetBinContent(23,52);
   deltaRLeptonPhotonStatus3->SetBinContent(24,59);
   deltaRLeptonPhotonStatus3->SetBinContent(25,53);
   deltaRLeptonPhotonStatus3->SetBinContent(26,50);
   deltaRLeptonPhotonStatus3->SetBinContent(27,60);
   deltaRLeptonPhotonStatus3->SetBinContent(28,60);
   deltaRLeptonPhotonStatus3->SetBinContent(29,67);
   deltaRLeptonPhotonStatus3->SetBinContent(30,69);
   deltaRLeptonPhotonStatus3->SetBinContent(31,89);
   deltaRLeptonPhotonStatus3->SetBinContent(32,62);
   deltaRLeptonPhotonStatus3->SetBinContent(33,56);
   deltaRLeptonPhotonStatus3->SetBinContent(34,35);
   deltaRLeptonPhotonStatus3->SetBinContent(35,31);
   deltaRLeptonPhotonStatus3->SetBinContent(36,16);
   deltaRLeptonPhotonStatus3->SetBinContent(37,24);
   deltaRLeptonPhotonStatus3->SetBinContent(38,33);
   deltaRLeptonPhotonStatus3->SetBinContent(39,23);
   deltaRLeptonPhotonStatus3->SetBinContent(40,16);
   deltaRLeptonPhotonStatus3->SetBinContent(41,18);
   deltaRLeptonPhotonStatus3->SetBinContent(42,10);
   deltaRLeptonPhotonStatus3->SetBinContent(43,5);
   deltaRLeptonPhotonStatus3->SetBinContent(44,14);
   deltaRLeptonPhotonStatus3->SetBinContent(45,2);
   deltaRLeptonPhotonStatus3->SetBinContent(46,4);
   deltaRLeptonPhotonStatus3->SetBinContent(47,7);
   deltaRLeptonPhotonStatus3->SetBinContent(48,12);
   deltaRLeptonPhotonStatus3->SetBinContent(49,5);
   deltaRLeptonPhotonStatus3->SetBinContent(50,7);
   deltaRLeptonPhotonStatus3->SetBinContent(51,6);
   deltaRLeptonPhotonStatus3->SetBinContent(52,4);
   deltaRLeptonPhotonStatus3->SetBinContent(53,4);
   deltaRLeptonPhotonStatus3->SetBinContent(54,2);
   deltaRLeptonPhotonStatus3->SetBinContent(55,2);
   deltaRLeptonPhotonStatus3->SetBinContent(56,4);
   deltaRLeptonPhotonStatus3->SetBinContent(57,2);
   deltaRLeptonPhotonStatus3->SetBinContent(58,1);
   deltaRLeptonPhotonStatus3->SetBinContent(61,1);
   deltaRLeptonPhotonStatus3->SetBinContent(62,2);
   deltaRLeptonPhotonStatus3->SetBinContent(63,2);
   deltaRLeptonPhotonStatus3->SetBinContent(68,1);
   deltaRLeptonPhotonStatus3->SetBinContent(72,1);
   deltaRLeptonPhotonStatus3->SetBinContent(73,1);
   deltaRLeptonPhotonStatus3->SetBinContent(75,1);
   deltaRLeptonPhotonStatus3->SetBinContent(76,1);
   deltaRLeptonPhotonStatus3->SetBinContent(79,1);
   deltaRLeptonPhotonStatus3->SetEntries(3504);
   deltaRLeptonPhotonStatus3->SetLineColor(2);
   deltaRLeptonPhotonStatus3->SetLineWidth(3);
   deltaRLeptonPhotonStatus3->Draw("same");
   
   TH1F *deltaRLeptonPhotonStatus3NoFilter = new TH1F("deltaRLeptonPhotonStatus3NoFilter","W#gamma#rightarrowl#nu#gamma+nj, l=e,#mu, n=0,1",100,0,10);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(1,5803);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(2,1105);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(3,688);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(4,446);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(5,307);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(6,265);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(7,214);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(8,167);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(9,142);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(10,150);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(11,95);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(12,102);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(13,82);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(14,84);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(15,75);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(16,70);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(17,67);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(18,67);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(19,56);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(20,47);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(21,57);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(22,36);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(23,52);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(24,59);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(25,53);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(26,50);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(27,60);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(28,60);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(29,67);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(30,69);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(31,89);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(32,62);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(33,56);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(34,35);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(35,31);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(36,16);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(37,24);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(38,33);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(39,23);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(40,16);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(41,18);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(42,10);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(43,5);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(44,14);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(45,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(46,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(47,7);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(48,12);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(49,5);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(50,7);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(51,6);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(52,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(53,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(54,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(55,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(56,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(57,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(58,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(61,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(62,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(63,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(68,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(72,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(73,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(75,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(76,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(79,1);
   deltaRLeptonPhotonStatus3NoFilter->SetEntries(11100);
   
   ptstats = new TPaveStats(0.6465517,0.6882591,0.8635057,0.8765182,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetLineColor(4);
   ptstats->SetTextAlign(12);
   ptstats->SetTextColor(4);
   text = ptstats->AddText("deltaRLeptonPhotonStatus3NoFilter");
   text->SetTextSize(0.0432996);
   text = ptstats->AddText("Entries = 11100  ");
   text = ptstats->AddText("Mean  = 0.5345");
   text = ptstats->AddText("RMS   = 0.9382");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   deltaRLeptonPhotonStatus3NoFilter->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(deltaRLeptonPhotonStatus3NoFilter->GetListOfFunctions());
   deltaRLeptonPhotonStatus3NoFilter->SetLineColor(4);
   deltaRLeptonPhotonStatus3NoFilter->SetLineStyle(2);
   deltaRLeptonPhotonStatus3NoFilter->SetLineWidth(3);
   deltaRLeptonPhotonStatus3NoFilter->GetXaxis()->SetTitle("#DeltaR(l,#gamma) matrix element level");
   deltaRLeptonPhotonStatus3NoFilter->GetXaxis()->SetRange(1,71);
   deltaRLeptonPhotonStatus3NoFilter->GetYaxis()->SetTitle("Events");
   deltaRLeptonPhotonStatus3NoFilter->Draw("same");
      tex = new TLatex(4.040754,234.567,"no gen. filter");

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#0000ff");
   tex->SetTextColor(ci);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(4.040754,104.3497,"with gen. filter");

   ci = TColor::GetColor("#ff0000");
   tex->SetTextColor(ci);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
