{
//=========Macro generated from canvas: c1/c1
//=========  (Mon Mar 22 21:15:09 2010) by ROOT version5.25/04
   TCanvas *c1 = new TCanvas("c1", "c1",299,94,700,544);
   c1->ToggleEventStatus();
   c1->Range(-0.8795332,-0.7507883,7.99228,3.692824);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetLogy();
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *deltaRLeptonPhotonStatus3NoFilter = new TH1F("deltaRLeptonPhotonStatus3NoFilter","Z#gamma#rightarrowl^{+}l^{-}#gamma+nj, l=e,#mu, n=0..2",100,0,10);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(1,943);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(2,172);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(3,111);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(4,83);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(5,49);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(6,43);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(7,39);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(8,45);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(9,38);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(10,34);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(11,22);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(12,24);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(13,21);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(14,24);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(15,24);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(16,23);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(17,24);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(18,23);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(19,26);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(20,33);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(21,36);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(22,42);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(23,31);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(24,57);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(25,54);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(26,61);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(27,96);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(28,84);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(29,73);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(30,102);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(31,139);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(32,363);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(33,214);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(34,118);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(35,81);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(36,58);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(37,52);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(38,41);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(39,40);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(40,34);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(41,18);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(42,19);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(43,13);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(44,8);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(45,15);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(46,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(47,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(48,6);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(49,4);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(50,2);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(51,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(52,3);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(57,1);
   deltaRLeptonPhotonStatus3NoFilter->SetBinContent(58,1);
   deltaRLeptonPhotonStatus3NoFilter->SetEntries(3674);
   
   TPaveStats *ptstats = new TPaveStats(0.7787356,0.8360324,0.9798851,0.9959514,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetLineColor(4);
   ptstats->SetTextAlign(12);
   ptstats->SetTextColor(4);
   TText *text = ptstats->AddText("deltaRLeptonPhotonStatus3NoFilter");
   text->SetTextSize(0.03678138);
   text = ptstats->AddText("Entries = 3674   ");
   text = ptstats->AddText("Mean  =  1.775");
   text = ptstats->AddText("RMS   =  1.469");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   deltaRLeptonPhotonStatus3NoFilter->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(deltaRLeptonPhotonStatus3NoFilter->GetListOfFunctions());
   deltaRLeptonPhotonStatus3NoFilter->SetLineColor(4);
   deltaRLeptonPhotonStatus3NoFilter->SetLineStyle(2);
   deltaRLeptonPhotonStatus3NoFilter->SetLineWidth(3);
   deltaRLeptonPhotonStatus3NoFilter->GetXaxis()->SetTitle("#DeltaR(l,#gamma) matrix element level");
   deltaRLeptonPhotonStatus3NoFilter->GetXaxis()->SetRange(1,71);
   deltaRLeptonPhotonStatus3NoFilter->GetYaxis()->SetTitle("Events");
   deltaRLeptonPhotonStatus3NoFilter->Draw("");
   
   TPaveText *pt = new TPaveText(0.01,0.9415587,0.4064368,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(1);
   text = pt->AddText("Z#gamma#rightarrowl^{+}l^{-}#gamma+nj, l=e,#mu, n=0..2");
   pt->Draw();
   
   TH1F *deltaRLeptonPhotonStatus3 = new TH1F("deltaRLeptonPhotonStatus3","deltaR lepton photon status 3",100,0,10);
   deltaRLeptonPhotonStatus3->SetBinContent(4,82);
   deltaRLeptonPhotonStatus3->SetBinContent(5,48);
   deltaRLeptonPhotonStatus3->SetBinContent(6,43);
   deltaRLeptonPhotonStatus3->SetBinContent(7,37);
   deltaRLeptonPhotonStatus3->SetBinContent(8,45);
   deltaRLeptonPhotonStatus3->SetBinContent(9,34);
   deltaRLeptonPhotonStatus3->SetBinContent(10,30);
   deltaRLeptonPhotonStatus3->SetBinContent(11,16);
   deltaRLeptonPhotonStatus3->SetBinContent(12,20);
   deltaRLeptonPhotonStatus3->SetBinContent(13,15);
   deltaRLeptonPhotonStatus3->SetBinContent(14,19);
   deltaRLeptonPhotonStatus3->SetBinContent(15,17);
   deltaRLeptonPhotonStatus3->SetBinContent(16,16);
   deltaRLeptonPhotonStatus3->SetBinContent(17,18);
   deltaRLeptonPhotonStatus3->SetBinContent(18,17);
   deltaRLeptonPhotonStatus3->SetBinContent(19,18);
   deltaRLeptonPhotonStatus3->SetBinContent(20,25);
   deltaRLeptonPhotonStatus3->SetBinContent(21,24);
   deltaRLeptonPhotonStatus3->SetBinContent(22,29);
   deltaRLeptonPhotonStatus3->SetBinContent(23,24);
   deltaRLeptonPhotonStatus3->SetBinContent(24,44);
   deltaRLeptonPhotonStatus3->SetBinContent(25,30);
   deltaRLeptonPhotonStatus3->SetBinContent(26,35);
   deltaRLeptonPhotonStatus3->SetBinContent(27,51);
   deltaRLeptonPhotonStatus3->SetBinContent(28,47);
   deltaRLeptonPhotonStatus3->SetBinContent(29,46);
   deltaRLeptonPhotonStatus3->SetBinContent(30,64);
   deltaRLeptonPhotonStatus3->SetBinContent(31,57);
   deltaRLeptonPhotonStatus3->SetBinContent(32,66);
   deltaRLeptonPhotonStatus3->SetBinContent(33,54);
   deltaRLeptonPhotonStatus3->SetBinContent(34,27);
   deltaRLeptonPhotonStatus3->SetBinContent(35,19);
   deltaRLeptonPhotonStatus3->SetBinContent(36,19);
   deltaRLeptonPhotonStatus3->SetBinContent(37,15);
   deltaRLeptonPhotonStatus3->SetBinContent(38,8);
   deltaRLeptonPhotonStatus3->SetBinContent(39,11);
   deltaRLeptonPhotonStatus3->SetBinContent(40,5);
   deltaRLeptonPhotonStatus3->SetBinContent(41,9);
   deltaRLeptonPhotonStatus3->SetBinContent(42,8);
   deltaRLeptonPhotonStatus3->SetBinContent(43,5);
   deltaRLeptonPhotonStatus3->SetBinContent(44,1);
   deltaRLeptonPhotonStatus3->SetBinContent(45,7);
   deltaRLeptonPhotonStatus3->SetBinContent(46,2);
   deltaRLeptonPhotonStatus3->SetBinContent(47,2);
   deltaRLeptonPhotonStatus3->SetBinContent(48,5);
   deltaRLeptonPhotonStatus3->SetBinContent(49,2);
   deltaRLeptonPhotonStatus3->SetBinContent(50,1);
   deltaRLeptonPhotonStatus3->SetBinContent(51,1);
   deltaRLeptonPhotonStatus3->SetBinContent(52,2);
   deltaRLeptonPhotonStatus3->SetBinContent(57,1);
   deltaRLeptonPhotonStatus3->SetBinContent(58,1);
   deltaRLeptonPhotonStatus3->SetEntries(1222);
   deltaRLeptonPhotonStatus3->SetLineColor(2);
   deltaRLeptonPhotonStatus3->SetLineWidth(3);
   deltaRLeptonPhotonStatus3->Draw("same");
   
   TH1F *deltaRLeptonPhotonStatus3 = new TH1F("deltaRLeptonPhotonStatus3","deltaR lepton photon status 3",100,0,10);
   deltaRLeptonPhotonStatus3->SetBinContent(1,943);
   deltaRLeptonPhotonStatus3->SetBinContent(2,172);
   deltaRLeptonPhotonStatus3->SetBinContent(3,111);
   deltaRLeptonPhotonStatus3->SetBinContent(4,83);
   deltaRLeptonPhotonStatus3->SetBinContent(5,49);
   deltaRLeptonPhotonStatus3->SetBinContent(6,43);
   deltaRLeptonPhotonStatus3->SetBinContent(7,39);
   deltaRLeptonPhotonStatus3->SetBinContent(8,45);
   deltaRLeptonPhotonStatus3->SetBinContent(9,38);
   deltaRLeptonPhotonStatus3->SetBinContent(10,34);
   deltaRLeptonPhotonStatus3->SetBinContent(11,22);
   deltaRLeptonPhotonStatus3->SetBinContent(12,24);
   deltaRLeptonPhotonStatus3->SetBinContent(13,21);
   deltaRLeptonPhotonStatus3->SetBinContent(14,24);
   deltaRLeptonPhotonStatus3->SetBinContent(15,24);
   deltaRLeptonPhotonStatus3->SetBinContent(16,23);
   deltaRLeptonPhotonStatus3->SetBinContent(17,24);
   deltaRLeptonPhotonStatus3->SetBinContent(18,23);
   deltaRLeptonPhotonStatus3->SetBinContent(19,26);
   deltaRLeptonPhotonStatus3->SetBinContent(20,33);
   deltaRLeptonPhotonStatus3->SetBinContent(21,36);
   deltaRLeptonPhotonStatus3->SetBinContent(22,42);
   deltaRLeptonPhotonStatus3->SetBinContent(23,31);
   deltaRLeptonPhotonStatus3->SetBinContent(24,57);
   deltaRLeptonPhotonStatus3->SetBinContent(25,54);
   deltaRLeptonPhotonStatus3->SetBinContent(26,61);
   deltaRLeptonPhotonStatus3->SetBinContent(27,96);
   deltaRLeptonPhotonStatus3->SetBinContent(28,84);
   deltaRLeptonPhotonStatus3->SetBinContent(29,73);
   deltaRLeptonPhotonStatus3->SetBinContent(30,102);
   deltaRLeptonPhotonStatus3->SetBinContent(31,139);
   deltaRLeptonPhotonStatus3->SetBinContent(32,363);
   deltaRLeptonPhotonStatus3->SetBinContent(33,214);
   deltaRLeptonPhotonStatus3->SetBinContent(34,118);
   deltaRLeptonPhotonStatus3->SetBinContent(35,81);
   deltaRLeptonPhotonStatus3->SetBinContent(36,58);
   deltaRLeptonPhotonStatus3->SetBinContent(37,52);
   deltaRLeptonPhotonStatus3->SetBinContent(38,41);
   deltaRLeptonPhotonStatus3->SetBinContent(39,40);
   deltaRLeptonPhotonStatus3->SetBinContent(40,34);
   deltaRLeptonPhotonStatus3->SetBinContent(41,18);
   deltaRLeptonPhotonStatus3->SetBinContent(42,19);
   deltaRLeptonPhotonStatus3->SetBinContent(43,13);
   deltaRLeptonPhotonStatus3->SetBinContent(44,8);
   deltaRLeptonPhotonStatus3->SetBinContent(45,15);
   deltaRLeptonPhotonStatus3->SetBinContent(46,4);
   deltaRLeptonPhotonStatus3->SetBinContent(47,2);
   deltaRLeptonPhotonStatus3->SetBinContent(48,6);
   deltaRLeptonPhotonStatus3->SetBinContent(49,4);
   deltaRLeptonPhotonStatus3->SetBinContent(50,2);
   deltaRLeptonPhotonStatus3->SetBinContent(51,1);
   deltaRLeptonPhotonStatus3->SetBinContent(52,3);
   deltaRLeptonPhotonStatus3->SetBinContent(57,1);
   deltaRLeptonPhotonStatus3->SetBinContent(58,1);
   deltaRLeptonPhotonStatus3->SetEntries(3674);
   deltaRLeptonPhotonStatus3->SetLineColor(4);
   deltaRLeptonPhotonStatus3->SetLineStyle(2);
   deltaRLeptonPhotonStatus3->SetLineWidth(3);
   deltaRLeptonPhotonStatus3->Draw("same");
      tex = new TLatex(4,100,"with gen. filter");

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   tex->SetTextColor(ci);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(4.002513,183.0595,"no gen. filter");

   ci = TColor::GetColor("#0000ff");
   tex->SetTextColor(ci);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
