#! /usr/bin/env sh
## pyroot
## ------
## Wrapper around the pyroot.py script.
## Jan Veverka, Caltech, 6 March 2012

## Call the pyroot.py in interactive mode and pass it all obtained arguments
env python -i $CMSSW_BASE/src/FWLite/Tools/python/pyroot.py $@

