#!/bin/bash
## Produces pdf plots of photon data/efficiency scale factors in 
## the current location.
## USAGE: vg-make-photon-sf-plots
PYTHON_SCRIPT=$CMSSW_BASE/src/Vgamma/Analysis/python/plotting/muonsf.py
python -i $PYTHON_SCRIPT

