#!/bin/bash
## Produces pdfs plots of electron data/efficiency scale factors in 
## the current location.
## USAGE: vg-make-electron-sf-plots
PYTHON_SCRIPT=$CMSSW_BASE/src/Vgamma/Analysis/python/plotting/electronsf.py
python -i $PYTHON_SCRIPT

