#!/bin/bash
## Runs the unit tests of Vgamma/Analysis
## USAGE: vg-run-unit-tests

echo "Running Vgamma/Analysis unit tests."

echo "VgExceptionTest ..."
VgExceptionTest

echo "VgCandidateTest ..."
VgCandidateTest

echo "VgLeafCandidateTest ..."
VgLeafCandidateTest

echo "VgEventTest ..."
VgEventTest

echo "VgEventSelectorTest ..."
VgEventTest

echo "Done."