import os
import datetime
from Vgamma.Analysis.bookkeeping.samples import eegamma
from Vgamma.Analysis.bookkeeping.samples import mumugamma
from Vgamma.Analysis.bookkeeping.samples import test

print 'START:', datetime.datetime.now().isoformat()

to_process = [
    #('EEG', eegamma), 
    #('MMG', mumugamma),
    ('TEST', test)
    ]
    
for name, collection in to_process:
    ## Give a heads-up
    print '==', name, '=='
    print 'Samples to process:', collection.keys()

    ## Loop over datasets
    for sample in (collection.values())[:]:
        total = sample.get_total_processed_events()
        if total == sample.total_processed_events:
            print sample.name, 'up to date'
        else:
            print sample.name, 'total processed events updating to', total
            filename = os.path.join(collection.package.__path__[0], 
                                    sample.name + '.py')
            with file(filename, 'a') as pyfile:
                line = ('%s.total_processed_events = '
                        '%s\n') % (sample.name, total)
                pyfile.write(line)
                #print filename
                #print line
    
    ### Generate injection command
    #print '= Injection Commands ='
    #outname = 'inject_processed_events_%(name)s.sh' % locals()
    #with open(outname, 'w') as injector:
        #for tot, name in [(sample.total_processed_events, sample.name)
            #for sample in collection.values()]:
            #lines = [
                #'## Injected automatically by %s generated by' % outname,
                #'## Vgamma/Analysis/bookkeeping/processedevents.py',
                #'%(name)s.total_processed_events = %(tot)s' % locals(),
                #''
                #]
            #commands = ['echo "%(l)s" >> %(name)s.py' % locals() 
                #for l in lines]
            ##injector.write('\n'.join(commands) + '\n\n')
            
    #injector.close()
    
print 'FIN:', datetime.datetime.now().isoformat()

#______________________________________________________________________________
if __name__ == '__main__':
    import user
