/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *
 * Make rho a parameter of RooKeysPdf.
 * 
 * Jan Veverka, Caltech, 8 May 2012 
 *****************************************************************************/

#ifndef FWLITE_TOOLS_ROORHOKEYSPDF_H
#define FWLITE_TOOLS_ROORHOKEYSPDF_H

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooRhoKeysPdf : public RooAbsPdf {
public:
  RooRhoKeysPdf() {} ; 
  RooRhoKeysPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _rho);
  RooRhoKeysPdf(const RooRhoKeysPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooRhoKeysPdf(*this,newname); }
  inline virtual ~RooRhoKeysPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy rho ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooRhoKeysPdf,1) // Your description goes here...
};
 
#endif
